version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rtoms
    ports:
      - "3307:3306"

  app:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  test:
    build: .
    command: ["pytest", "--tb=short", "-q"]
    depends_on:
      - db
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: rtoms
      DB_HOST: db
    volumes:
      - .:/code
