name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx fastapi
          pip install "pytest-asyncio>=0.20"
          pip install sqlmodel aiomysql
          pip install -r requirements.txt || echo "Skip requirements if not found"
          TEST_ENV=1 pytest tests --disable-warnings
          
      - name: Run tests
        run: |
          python -m pytest tests --disable-warnings
